### ISSUE TITLE
Connecting to server only specifying `postgres` user

### ISSUE THREAD

**Issue by fpietka** [amjith/pgcli#101]
When I usually connect to a postgres server I just type the following:

    psql -U postgres

This automatically connects me to postgres database. Here, `pgcli` is connecting me to my current user database.
I don't know if this is a Debian specificity, but I coudn't see anything about it in my config files nor on postgresql documentation.
Isn't it a difference of behavior?

**Comment by amjith** [comment]
You're right, this discrepancy should be fixed. Right now we're falling back to the $USER env var to use for both user name and database name. But if a Username is provided and the database name is omitted then we should fall back to the Username as the database name. 

Thanks for reporting it. I'll fix it soon.
