### ISSUE TITLE
how to use pgcli on win7

### ISSUE THREAD

**Issue by jerome-peng** [amjith/pgcli#108]
my pc is win7 32bit system, i want to use pgcli, then i get some errors.

my operation is bellow:

1 download python3.4.2 from https://www.python.org/downloads/release/python-342/
 installed in D:\Python‍

2 install python-pip
   download get-pip.py from ‍https://bootstrap.pypa.io/get-pip.py to D:\‍
   run command: python d:\get-pip.py‍

3  pip install pgcli ‍
D:\Python\Scripts>pip install pgcli
Collecting pgcli
  Downloading pgcli-0.11.0.tar.gz
Collecting click>=3.2 (from pgcli)
  Downloading click-3.3-py2.py3-none-any.whl (58kB)
    100% |################################| 61kB 71kB/s ta 0:00:011
Collecting Pygments>=2.0 (from pgcli)
  Downloading Pygments-2.0.1-py3-none-any.whl (672kB)
    100% |################################| 675kB 347kB/s ta 0:00:01
Collecting jedi==0.8.1 (from pgcli)
  Downloading jedi-0.8.1.tar.gz (304kB)
    100% |################################| 307kB 196kB/s ta 0:00:01
Collecting prompt-toolkit==0.25 (from pgcli)
  Downloading prompt_toolkit-0.25.tar.gz (93kB)
    100% |################################| 94kB 255kB/s ta 0:00:01
Collecting psycopg2>=2.5.4 (from pgcli)
  Downloading psycopg2-2.5.4.tar.gz (682kB)
    100% |################################| 684kB 251kB/s ta 0:00:01
Collecting sqlparse>=0.1.14 (from pgcli)
  Downloading sqlparse-0.1.14.tar.gz (55kB)
    100% |################################| 57kB 203kB/s ta 0:00:011
Collecting docopt (from prompt-toolkit==0.25->pgcli)
  Downloading docopt-0.6.2.tar.gz
Collecting six>=1.8.0 (from prompt-toolkit==0.25->pgcli)
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit==0.25->pgcli)
  Downloading wcwidth-0.1.4-py2.py3-none-any.whl
Installing collected packages: wcwidth, six, docopt, sqlparse, psycopg2, prompt-
toolkit, jedi, Pygments, click, pgcli

  Running setup.py install for docopt
  Running setup.py install for sqlparse
    Fixing build\lib\sqlparse\exceptions.py build\lib\sqlparse\filters.py build\
lib\sqlparse\formatter.py build\lib\sqlparse\functions.py build\lib\sqlparse\key
words.py build\lib\sqlparse\lexer.py build\lib\sqlparse\pipeline.py build\lib\sq
lparse\sql.py build\lib\sqlparse\tokens.py build\lib\sqlparse\utils.py build\lib
\sqlparse\__init__.py build\lib\sqlparse\engine\filter.py build\lib\sqlparse\eng
ine\grouping.py build\lib\sqlparse\engine\__init__.py
    Fixing build\lib\sqlparse\exceptions.py build\lib\sqlparse\filters.py build\
lib\sqlparse\formatter.py build\lib\sqlparse\functions.py build\lib\sqlparse\key
words.py build\lib\sqlparse\lexer.py build\lib\sqlparse\pipeline.py build\lib\sq
lparse\sql.py build\lib\sqlparse\tokens.py build\lib\sqlparse\utils.py build\lib
\sqlparse\__init__.py build\lib\sqlparse\engine\filter.py build\lib\sqlparse\eng
ine\grouping.py build\lib\sqlparse\engine\__init__.py
  Running setup.py install for psycopg2
    building 'psycopg2._psycopg' extension
    error: Unable to find vcvarsall.bat
    Complete output from command D:\Python\python.exe -c "import setuptools, tok
enize;__file__='C:\\Users\\JEROME~1\\AppData\\Local\\Temp\\pip-build-iu4ck56w\\p
sycopg2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read()
.replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\JEROME~1\A
ppData\Local\Temp\pip-t1lhcf2s-record\install-record.txt --single-version-extern
ally-managed --compile:
    running install

    running build

    running build_py

    creating build

    creating build\lib.win32-3.4

    creating build\lib.win32-3.4\psycopg2

    copying lib\errorcodes.py -> build\lib.win32-3.4\psycopg2

    copying lib\extensions.py -> build\lib.win32-3.4\psycopg2

    copying lib\extras.py -> build\lib.win32-3.4\psycopg2

    copying lib\pool.py -> build\lib.win32-3.4\psycopg2

    copying lib\psycopg1.py -> build\lib.win32-3.4\psycopg2

    copying lib\tz.py -> build\lib.win32-3.4\psycopg2

    copying lib\_json.py -> build\lib.win32-3.4\psycopg2

    copying lib\_range.py -> build\lib.win32-3.4\psycopg2

    copying lib\__init__.py -> build\lib.win32-3.4\psycopg2

    creating build\lib.win32-3.4\psycopg2\tests

    copying tests\dbapi20.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\dbapi20_tpc.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\testconfig.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\testutils.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_async.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_bugX000.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_bug_gc.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_cancel.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_connection.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_copy.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_cursor.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_dates.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_extras_dictcursor.py -> build\lib.win32-3.4\psycopg2\test
s

    copying tests\test_green.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_lobject.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_module.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_notify.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_psycopg2_dbapi20.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_quote.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_transaction.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_types_basic.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_types_extras.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_with.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\__init__.py -> build\lib.win32-3.4\psycopg2\tests

    Skipping implicit fixer: buffer

    Skipping implicit fixer: idioms

    Skipping implicit fixer: set_literal

    Skipping implicit fixer: ws_comma

    running build_ext

    building 'psycopg2._psycopg' extension

    error: Unable to find vcvarsall.bat

    ----------------------------------------
    Command "D:\Python\python.exe -c "import setuptools, tokenize;__file__='C:\\
Users\\JEROME~1\\AppData\\Local\\Temp\\pip-build-iu4ck56w\\psycopg2\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record C:\Users\JEROME~1\AppData\Local\Temp\pi
p-t1lhcf2s-record\install-record.txt --single-version-externally-managed --compi
le" failed with error code 1 in C:\Users\JEROME~1\AppData\Local\Temp\pip-build-i
u4ck56w\psycopg2

i get some help from google: maybe i need install MinGW ,so i install MinGW

then i retry step 3

D:\>pip install pgcli
Collecting pgcli
  Using cached pgcli-0.11.0.tar.gz
Collecting click>=3.2 (from pgcli)
  Using cached click-3.3-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from pgcli)
  Using cached Pygments-2.0.1-py3-none-any.whl
Collecting jedi==0.8.1 (from pgcli)
  Using cached jedi-0.8.1.tar.gz
Collecting prompt-toolkit==0.25 (from pgcli)
  Using cached prompt_toolkit-0.25.tar.gz
Collecting psycopg2>=2.5.4 (from pgcli)
  Using cached psycopg2-2.5.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): sqlparse>=0.1.14 in d:
\python\lib\site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): docopt in d:\python\li
b\site-packages (from prompt-toolkit==0.25->pgcli)
Requirement already satisfied (use --upgrade to upgrade): six>=1.8.0 in d:\pytho
n\lib\site-packages (from prompt-toolkit==0.25->pgcli)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in d:\python\l
ib\site-packages (from prompt-toolkit==0.25->pgcli)
Installing collected packages: psycopg2, prompt-toolkit, jedi, Pygments, click,
pgcli
  Running setup.py install for psycopg2
    building 'psycopg2._psycopg' extension
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    Complete output from command D:\Python\python.exe -c "import setuptools, tok
enize;__file__='C:\\Users\\JEROME~1\\AppData\\Local\\Temp\\pip-build-fj7njncs\\p
sycopg2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read()
.replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\JEROME~1\A
ppData\Local\Temp\pip-8ay3ynz7-record\install-record.txt --single-version-extern
ally-managed --compile:
    running install

    running build

    running build_py

    creating build

    creating build\lib.win32-3.4

    creating build\lib.win32-3.4\psycopg2

    copying lib\errorcodes.py -> build\lib.win32-3.4\psycopg2

    copying lib\extensions.py -> build\lib.win32-3.4\psycopg2

    copying lib\extras.py -> build\lib.win32-3.4\psycopg2

    copying lib\pool.py -> build\lib.win32-3.4\psycopg2

    copying lib\psycopg1.py -> build\lib.win32-3.4\psycopg2

    copying lib\tz.py -> build\lib.win32-3.4\psycopg2

    copying lib\_json.py -> build\lib.win32-3.4\psycopg2

    copying lib\_range.py -> build\lib.win32-3.4\psycopg2

    copying lib\__init__.py -> build\lib.win32-3.4\psycopg2

    creating build\lib.win32-3.4\psycopg2\tests

    copying tests\dbapi20.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\dbapi20_tpc.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\testconfig.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\testutils.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_async.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_bugX000.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_bug_gc.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_cancel.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_connection.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_copy.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_cursor.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_dates.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_extras_dictcursor.py -> build\lib.win32-3.4\psycopg2\test
s

    copying tests\test_green.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_lobject.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_module.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_notify.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_psycopg2_dbapi20.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_quote.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_transaction.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_types_basic.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_types_extras.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\test_with.py -> build\lib.win32-3.4\psycopg2\tests

    copying tests\__init__.py -> build\lib.win32-3.4\psycopg2\tests

    Skipping implicit fixer: buffer

    Skipping implicit fixer: idioms

    Skipping implicit fixer: set_literal

    Skipping implicit fixer: ws_comma

    running build_ext

    building 'psycopg2._psycopg' extension

    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    ----------------------------------------
    Command "D:\Python\python.exe -c "import setuptools, tokenize;__file__='C:\\
Users\\JEROME~1\\AppData\\Local\\Temp\\pip-build-fj7njncs\\psycopg2\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record C:\Users\JEROME~1\AppData\Local\Temp\pi
p-8ay3ynz7-record\install-record.txt --single-version-externally-managed --compi
le" failed with error code 1 in C:\Users\JEROME~1\AppData\Local\Temp\pip-build-f
j7njncs\psycopg2

so i need to install Microsoft Visual C++ 10.0 ?

so much to install!

Is there a simple way to fix this problem,  i just want to use pgcli, the simple  the better.

**Comment by amjith** [comment]
:(

I'm sorry you're having to install so many different things. I believe this is due to the required  dependencies for psycopg2. But I have limited experience with installing python packages in Windows so I'm not the best person to give you advice. I hope someone else has a solution for this. 

I've also created a new issue #109 to try and create a single executable using py2exe or something similar that will ease the pain. I would appreciate if someone has the time and expertise to contribute for that.

**Comment by darikg** [comment]
install psycopg2 from a binary [here](http://www.stickpeople.com/projects/python/win-psycopg/) instead of through pip

**Comment by amjith** [comment]
@jerome-peng Were you able to get pscypg2 installed on Win 7 using the binary suggested by darikg? 

Did you manage to get `pgcli` working in Win 7?

**Comment by jerome-peng** [comment]
yes ,i use darikg's suggestion install psycopg2, then use pip install pgcli, the install process is normal.
here is log:

  Running setup.py install for pgcli
    Installing pgcli-script.py script to D:\Python\Scripts
    Installing pgcli.exe script to D:\Python\Scripts
    Installing pgcli.exe.manifest script to D:\Python\Scripts
Successfully installed Pygments-2.0.1 click-3.3 jedi-0.8.1 pgcli-0.12.0 prompt-t
oolkit-0.26

D:\>pgcli -h 192.168.20.19 -U afc edb

then i lose of control, it out of response. Even i can't use "Ctrl" +"C" to disrupt it.

**Comment by jerome-peng** [comment]
:)
it works !
D:\Python>pgcli -h 192.168.20.19 -p 5444 -U afc edb

it must add -h -p option,   i thought i can't input the port  becasue use default

**Comment by amjith** [comment]
It uses the default port of 5432, if it is not specified explicitly with the -p option. 

I'm guessing you have some other service listening on 5432 and pgcli is trying to connect to that port.

**Comment by amjith** [comment]
Looks like you got it working. I'll close this ticket for now.

**Comment by jerome-peng** [comment]
yes it working. thanks all.
