### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by PeteJodo** [amjith/pgcli#118]
Installation fails if you don't have one or some of the following packages:
- python2.7-dev
- libevent-dev

The error: `error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
I would put in a PR to add this info to the README but I don't know which one fixed it or if it was both and don't want to put false info in it so figured I'd at least leave this here

**Comment by amjith** [comment]
You're right the detailed instructions in the readme should have that information. 

Feel free to make a PR. If not, I'll make the necessary changes later tonight when I get home. Thanks!

**Comment by amjith** [comment]
Readme is now updated. 

Thanks for reporting it. :umbrella:
