### ISSUE TITLE
Auto-completion does not work for LIMIT sql keyword

### ISSUE THREAD

**Issue by TarImre** [amjith/pgcli#125]
When I try to use Tab key after the next command, the LIMIT option does not appear.
```testdb> SELECT * FROM test_table L```

**Comment by TarImre** [comment]
I use pgcli 0.13.0 pip package.

**Comment by amjith** [comment]
Yep! You're right. Looks like I don't have the LIMIT listed in the Keywords (https://github.com/amjith/pgcli/blob/master/pgcli/pgcompleter.py#L12). 

I'll fix that. 

Thanks for reporting. :)
