### ISSUE TITLE
Autocomplete "LIMIT" keyword

### ISSUE THREAD

**Issue by veegee** [amjith/pgcli#130]
"LIMIT" doesn't seem to be autocompleting, or even showing up in the popup menu.

**Comment by amjith** [comment]
Yeah, I missed that keyword in the original list. It is now fixed in master. It'll be available in the next release (probably this weekend).

**Comment by amjith** [comment]
This is now added to master. If you have time please try out the latest from master. Thanks!

```
pip install -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

**Comment by amjith** [comment]
Version 0.14.0 released to PyPI. 

```
pip install -U pgcli
```
