### ISSUE TITLE
Use ANSI terminal colours instead of 256 colour mode

### ISSUE THREAD

**Issue by veegee** [amjith/pgcli#131]
Many people have set their terminal colour scheme to something like Solarized. By using 256 colours, you're ignoring the custom ANSI colours that have been set, and text becomes hard to read. It is always best to stick to ANSI 16-colour mode.

**Comment by amjith** [comment]
Hrm. This might be harder to do, since I rely on prompt_toolkit library to handle all of that for me. But I'll check if there is an easy way to detect and set the color mode accordingly.

**Comment by tonymcdaniel** [comment]
If changing the color mode is difficult, would it be possible to add a setting in the .pgclirc file to disable syntax highlighting? I'm using Solarized in iTerm2 on a Mac and certain characters in my queries disappear against the background color.

**Comment by amjith** [comment]
@tonymcdaniel Yes. I'll add that feature. It's on my todo list to make the colorschemes selectable from the config file, I'll also add an option to turn it off completely.

**Comment by amjith** [comment]
Ok. I've added the ability to pick a different color scheme via the ~/.pgclirc config file to master. 

You can install directly from master using the following command: 

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

Then add this line to your config file (~/.pgclirc)

```
syntax_style = native
```

All the built-in pygments styles are available to choose: 

```
# manni, igor, xcode, vim, autumn, vs, rrt, 
# native, perldoc, borland, tango, emacs, friendly, monokai, paraiso-dark, 
# colorful, murphy, bw, pastie, paraiso-light, trac, default, fruity
```

I still have to figure out how to completely turn off all coloring. 

If you can try it out and give me some feedback whether it's satisfactory, I'd appreciate it.

**Comment by veegee** [comment]
I think there should be a way to define your own colours for all UI elements. That might solve the issue.

**Comment by amjith** [comment]
Version 0.15.4 released to PyPI.
