### ISSUE TITLE
postgres is case-insensitive for table names, but pgcli isn't

### ISSUE THREAD

**Issue by jeremybmerrill** [amjith/pgcli#141]
postgresql is case-insensitive for table names (technically, downcasing all of them), so `DEC_00_SF3_QTP16` refers to the same table as `dec_00_sf3_qtp16`. 

For reasons that are fairly abstruse, I refer to my tables in my codebase in partial/all caps, e.g. `DEC_00_SF3_QTP16`, so in my head, that's the name of my table. However, in pgcli, when I try to autocomplete from `DEC`, I get nothing, and have to downcase what I've typed. Could you make the autocomplete be case-insensitive?

BTW: pgcli is awesome, thanks for your work! I'm very glad to have found this.

**Comment by amjith** [comment]
You serious? I thought you could have case-sensitive table names but you'd have to use double quotes to preserve the casing. 

Can you try SELECT * FROM "DEC<tab>  ? 

I believe that should work.

**Comment by jeremybmerrill** [comment]
Sorry, maybe I explained this poorly. The issue is with an inconsistency between postgres and pgcli's treatment of case in the context of pgcli's autocomplete behavior.

PG is case-insensitive -- it stores my table as `dec_...`, but lets me query it like `DEC_...`. pgcli won't autocomplete from `DEC_`. My expected behavior is that pgcli would let me autocomplete from `DEC_` (because postgres accepts queries case-insensitively).

Although maybe you're saying that this would break in the (relatively rare?) instance that someone had an actually upper-cased table name (using the double quote method you mention)?

**Comment by amjith** [comment]
Got it. 

Try the latest master. You can install from master using pip as follows:

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

**Comment by amjith** [comment]
Fixed by c08d4a51e5540e7ada833bd4beb6ba2f4bdba37e

**Comment by jeremybmerrill** [comment]
Tested and it works great! Thanks very much for your help. As I said before, great tool!

**Comment by amjith** [comment]
Thank you for checking it. I'm glad it works. I'll release the new version to PyPI this weekend.
