### ISSUE TITLE
Booleans are displayed as 0 1 and not as false true 

### ISSUE THREAD

**Issue by pmontrasio** [amjith/pgcli#143]
This is pgcli 0.13:

    db> select boolean_column from table;
    +----------------------+
    |       boolean_column |
    |----------------------|
    |                    1 |
    |                    0 |
    |                    1 |
    |                    0 |

psql reports them correctly:

    db=> select boolean_column from table;
     boolean_column 
    --------------------
     t
     f
     t
     f

That could mislead people believing that a column has an integer data type instead of a boolean.

**Comment by amjith** [comment]
Yes. This is a valid concern. I'll see if I can register a handler for booleans in psycopg2 to return them as strings.

**Comment by amjith** [comment]
Fixed in master. 6e3da4c5b1d1369348dd333c8510f516ec76a5cf

Can you try the latest HEAD? You can install directly from master: 

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

**Comment by pmontrasio** [comment]
It works, I get ```False``` and ```True``` now. That could be better (more clear) or worse (more verbose) than pgsql ```f``` and ```t``` but I'm not a large enough sample to judge.
