### ISSUE TITLE
horizontal scrolling view of queries output

### ISSUE THREAD

**Issue by edoardoc** [amjith/pgcli#147]
Given the huge amount of data that one has to browse horizontally using pgcli, it would be a very big help being able to scroll (with cursor keys or similar) like in a window view
There is a few examples of CLI programs that allow viewport scrolling, one of this is vi, and also less can do it
An implementation idea, rather that having to actually recreate the scroll is to add a parameter to the query launcher so that the output would be shown inside a spawned process using an external less -S command.

**Comment by wbolster** [comment]
`pgcli` uses `less` already, so if you just type `-S`, followed by `Enter`, while the results are being shown through `less`, you get a wide display in which you can scroll horizontally using arrow keys (and any other way `less` supports.

**Comment by edoardoc** [comment]
great to know, lets close this then

**Comment by amjith** [comment]
Awesome! I had no idea you could do that with `less`. 

Thank you @wbolster.
