### ISSUE TITLE
Having an error with less

### ISSUE THREAD

**Issue by davidlonjon** [amjith/pgcli#148]
Hi there,

First great tool! Thank you for your effort :)

I installed the tool on my Linux VM (Ubuntu 12.04.5 LTS) and everything went well. I installed it with the dependencies mentioned in the detailed instructions. 

I can login to my PostgreSQL instance but every time I run a command in pgcli I received the following message: `There is no no-initXF option ("less --help" for help)`
and nothing is returned except the "Command Time" and "format Time" output.

It seems a problem with Less pager. Google the problem but cannot find anything related to it.
Would you have any idea? The output of my `$less --version` is: `less 444`

**Comment by amjith** [comment]
That's interesting. I'm overriding the LESS env var to not clear the screen while inside the pgcli environment, I didn't think of the `--no-init` option. I've got a fix for that in the master. Would you mind trying it out? 

You can install it directly from the git repo as follows: 

```
pip uninstall pgcli         # This will uninstall the existing pgcli.
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

**Comment by davidlonjon** [comment]
Done it and it fixed the issue :)
Thanks!

**Comment by amjith** [comment]
0.15.4 released to PyPI.
