### ISSUE TITLE
Install fails on !# linux

### ISSUE THREAD

**Issue by archaeogeek** [amjith/pgcli#153]
Followed all instructions to install dependencies, made sure setuptools was updated. I get the following error with pip install:
/usr/local/bin/pip run on Thu Feb 12 18:50:18 2015
Downloading/unpacking pgcli
  Getting page https://pypi.python.org/simple/pgcli/
  URLs to search for versions for pgcli:
  * https://pypi.python.org/simple/pgcli/
  Analyzing links from page https://pypi.python.org/simple/pgcli/
    Found link https://pypi.python.org/packages/source/p/pgcli/pgcli-0.15.4.tar.gz#md5=373ea29d82c37f6339ae6a4ae4e8fecb (from https://pypi.python.org/simple/pgcli/), version: 0.15.4
  Downloading pgcli-0.15.4.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/p/pgcli/pgcli-0.15.4.tar.gz#md5=373ea29d82c37f6339ae6a4ae4e8fecb (from https://pypi.python.org/simple/pgcli/)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 292, in run_egg_info
    logger.notify('Running setup.py (path:%s) egg_info for package %s' % (self.setup_py, self.name))
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 265, in setup_py
    import setuptools
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

and something pretty similar when I install from the repository:
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

**Comment by amjith** [comment]
Sorry about the trouble. 

I believe this is a mismatch between the setuptools version and pip. 

Can you confirm that you can successfully install other packages? Say `pip install prompt_toolkit`. 

Since you mentioned that you already upgraded setuptools, I presume you're on the latest version there. Did you also try upgrading pip? 

You can try `pip install -U pip` to upgrade it. 

If you still have the same problem after all that upgrade, you can always try using easy_install. 

`easy_install pgcli`

**Comment by archaeogeek** [comment]
Thanks for the quick response, it looks like I have a problem with both pip and easy_install- I upgraded pip as you suggested, installing other packages gives the same error, and easy_install also gives the same error. I'll do some digging, but feel free to close this issue as it's not a problem with pgcli

**Comment by amjith** [comment]
I'd like to keep this issue open. 

If you find a solution for it please post it here, if not I hope someone else who has a solution might post something. :)

**Comment by archaeogeek** [comment]
Thanks- I actually ended up completely uninstalling pip and reinstalling from my package manager- but I ended up with different errors:
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.15.4', 'console_scripts', 'pgcli')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 12, in <module>
    from prompt_toolkit import CommandLineInterface, AbortAction, Exit
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/__init__.py", line 14, in <module>
    from .buffer import Buffer
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/buffer.py", line 12, in <module>
    from .utils import EventHook
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/utils.py", line 56, in <module>
    _CHAR_SIZES_CACHE = [wcwidth(six.unichr(i)) for i in range(0, 64000)]
AttributeError: 'module' object has no attribute 'unichr'

I made sure that six was up to date, which was the only thing I could see here- but otherwise I haven't managed to progress it at all

**Comment by amjith** [comment]
Does this error happens when you try to install or when you launch?
Can you also tell me what version of six you have installed on this machine? 

You can get a list of all installed python packages with their versions using `pip freeze`.

The version of six should be 1.9. I do see the unichr in the six module here: https://bitbucket.org/gutworth/six/src/986089f3d04e468458cc9f5b9b3be26fb3d75ade/six.py?at=default#cl-611

**Comment by archaeogeek** [comment]
I've just tested this and pip freeze | grep six reports version 1.9.0

Thanks

Jo

**Comment by amjith** [comment]
Hrm. That's odd. I suspect that prompt_toolkit isn't picking the right six module at runtime. Are you running this in a virtualenv or is it installed system wide? 

Can you try uninstalling 'six'? Try running `pip uninstall six`, please run it twice. I've noticed that sometimes it is necessary to uninstall a package twice to completely wipe it. :(

After the uninstall, install it again using `pip install six`. Then try again?

**Comment by archaeogeek** [comment]
Hi,

This is system wide. I completely uninstalled pip, pgcli, six, prompt_tools etc and then reinstalled them- and still get the same error when running pgcli, sorry!

Jo

**Comment by archaeogeek** [comment]
Ha!

I cloned the repository to my local machine, and followed the development instructions for installing it from the local copy, and it worked fine!

Jo

**Comment by amjith** [comment]
I guess that's good. 

I have no idea what was causing the problem and why the development version works. :(

Sorry you had to go through so much trouble.

**Comment by archaeogeek** [comment]
Crunchbang linux can be a bit difficult sometimes, so I'm used to it! Happy to close this though since it's now working for me. Thanks for your help!

**Comment by amjith** [comment]
:+1:

**Comment by remram44** [comment]
I'm also affected. I'm using pip 6.0.8 (current) and setuptools 14.3.1 (__version__ 0.6; current) on Ubuntu.

**Comment by amjith** [comment]
@remram44 What is the error message? I really wish I could reproduce it, so I can report to setuptools. :(

Did you try easy_install pgcli? I've heard from many sources that it succeeds even when pip fails.

**Comment by remram44** [comment]
Somehow rebuilt the virtualenv and it worked? The error was the same, pip importing setuptools and setuptools importing pkg_resources.packaging, which wasn't found (although setuptools outside of pip works fine).

**Comment by amjith** [comment]
Aha. I'm wondering if the virtualenv was created by an older version of setuptools and when pip and setuptools were upgraded inside the virtualenv it probably didn't work? 

That's good to know, because I can recommend it to people if I run into this issue in the future. 

Thanks for replying. I'm glad you got it working. :)

**Comment by sarang4** [comment]
I'm also facing same issue.
Pip version pip 6.0.8
and setuptools version upgraded to 14.3.1

**Comment by amjith** [comment]
@sarang4 Are you installing inside a virtualenv? If so, can you try it in a fresh new virtualenv after you upgraded setuptools and pip? 

If that doesn't work, can you try easy_install? 

And what version of Python are you using?

**Comment by sarang4** [comment]
@amjith No, I was installing on my system. I have uninstalled it and back to 8.2.1 version. It seems there is bug in setuptools 14.3.1.

**Comment by amjith** [comment]
@sarang4 Were you able to install it using setuptools 8.2.1?

**Comment by charz** [comment]
Hi all,
I got same problem in setuptools v14.3.1 and created a bug for it.

**Comment by amjith** [comment]
Thank you @charz for chasing that bug and filing a bug report. I'll recommend setuptools 8.2.1 for the future.
