### ISSUE TITLE
Odd completion behavior with keywords starting with "d"

### ISSUE THREAD

**Issue by drocco007** [amjith/pgcli#159]
With pgcli 0.15.4, I get odd behavior when completing keywords starting with "d"; before hitting [Tab]:

![image](https://cloud.githubusercontent.com/assets/1424858/6355493/75ffcd5a-bc24-11e4-9c32-995f38d02623.png)

After hitting [Tab]

![image](https://cloud.githubusercontent.com/assets/1424858/6355521/9cf4a818-bc24-11e4-86e9-7607f39a1215.png)

The "DESCRIBE" keyword (or its "describe" doppelganger in the menu) seems to clobber the other keywords. If I type enough disambiguating characters, the completion works correctly, e.g. "dec" [Tab] correctly completes to "DECIMAL"

**Comment by drocco007** [comment]
Around line 212 of pgcompleter.py, we have this (added in 78288101):

            elif suggestion['type'] == 'keyword':
                keywords = self.keywords + self.special_commands

This is what is causing the problem, since describe is being pulled in as a special command (the '\' prefix special commands are as well… :-/). This also seems to contradict the comment earlier in the file (around line 72):

    def extend_special_commands(self, special_commands):
        # Special commands are not part of all_completions since they can only
        # be at the beginning of a line.
        self.special_commands.extend(special_commands)

**Comment by amjith** [comment]
You're right. The comment got outdated and I failed to listen to 'past me'. Thanks for fixing it with the PR.
