### ISSUE TITLE
Can't start (pkg_resources.DistributionNotFound: jedi>=0.8.1)

### ISSUE THREAD

**Issue by jackmaney** [amjith/pgcli#16]
It seems as though `pgcli` can't find a package called `jedi`:

```
$ pgcli localhost
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2912, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 550, in _build_master
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 563, in _build_from_requirements
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 742, in resolve
pkg_resources.DistributionNotFound: jedi>=0.8.1
```

However, I already have a sufficient version of this package installed:

```
$ python
Python 2.7.9 (default, Dec 15 2014, 10:15:39)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> jedi.__version__
'0.8.1-final0'
```

Am I missing anything obvious here?

Thank you for your time.

**Comment by jackmaney** [comment]
I should add that I'm using the Python 2.7.9 provided by Homebrew.

**Comment by amjith** [comment]
Can you try `pip install jedi==0.8.1`? 

There was a recently a change in pip that disallowed packages that didn't conform to PEP 440 from being installed. It was rectified by Jedi just two days ago. So it's worth upgrading jedi. 

Ref: https://github.com/davidhalter/jedi/issues/521

**Comment by jackmaney** [comment]
A `pip install jedi==0.8.1` seemed to do the trick. I'm having another issue in connecting to a server, however. I'll open up a separate issue for that.

Thanks!

**Comment by adregan** [comment]
I had the same error and a quick `pip freeze` told me the jedi I had installed was `jedi==0.8.1-final0`.

Explicitly installing `pip install jedi==0.8.1` fixed the problem, but I'm not sure where the issue started.
