### ISSUE TITLE
Table header shows "?column?" as column name

### ISSUE THREAD

**Issue by wbolster** [amjith/pgcli#166]
This query:

```sql
SELECT jsonb_column->>'field' FROM tbl;
```

...results in an output table with a column named `?column?`. Is this intended?

For comparison, the query:

```sql
SELECT jsonb_column->>'field' AS "title" FROM tbl;
```

... shows `title` as the column title.

**Comment by amjith** [comment]
@wbolster That behavior is inherent to Postgres. When it return the results it returns the metadata such as the table name, column name etc. In this case it's returning the column name as `?column?`. 

This behavior is consistent with `psql` as I see the same output in psql as well.

**Comment by wbolster** [comment]
Ah, didn't know this was a PostgreSQL thing; I assumed it was some missing formatting stuff on the `pgcli` side. Nevermind, closing.
