### ISSUE TITLE
raise messages not displayed (unless exception)

### ISSUE THREAD

**Issue by jabclab** [amjith/pgcli#177]
When using `raise` for debugging purposes the output is not shown in `pgcli` (even if `client_min_messages` is set accordingly). Here's an example using **0.16.2**:

```
-- Base function
create or replace function foo() returns void as $func$
  raise notice 'hello world!';
$func$ language plpgsql;
```

Here's the `pgcli` output:
```
jake> select foo()
+-------+
| foo   |
|-------|
|       |
+-------+
SELECT 1
Command Time: 2.86102294922e-06
Format Time: 0.000157833099365
```

And here's the `psql` output:
```
jake=# select foo();
NOTICE:  hello world!
 foo
-----

(1 row)
```

**Comment by amjith** [comment]
Interesting! I hadn't thought about stored procedures and doing exceptions inside them. I'll have to check how psycopg2 returns them.

Thanks for reporting it. I'll take a look soon. :)

**Comment by amjith** [comment]
@jabclab I'm not able to create that function. Here's the output from psql: 

```
misago=# create or replace function foo() returns void as $func$
misago$#   raise notice 'hello world!';
misago$# $func$ language plpgsql;
ERROR:  syntax error at or near "raise"
LINE 2:   raise notice 'hello world!';
          ^
misago=#
```
Am I missing something?

**Comment by jabclab** [comment]
@amjith sorry, my bad- I didn't put the `begin` and `end` around the plpgsql function body:

```
create or replace function foo() returns void as $$
begin
  raise notice 'hello world!';
end $$ language plpgsql;
```

**Comment by amjith** [comment]
Alright, I finally found a way to get the notices out from psycopg2 (http://initd.org/psycopg/docs/connection.html?highlight=notice#connection.notices). I'll get that feature added soon.

**Comment by jabclab** [comment]
Great, thanks @amjith :smile:

**Comment by amjith** [comment]
This is now fixed in master.

Install from master using the following command, to try it out.

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```
