### ISSUE TITLE
Quote column names with spaces when autocompleting

### ISSUE THREAD

**Issue by hammer** [amjith/pgcli#178]
If I have a column name like `Gene Symbol` the autocomplete should add the double quotes for me and give me `"Gene Symbol"`.

**Comment by amjith** [comment]
It does. But it does it in a weird way. When you type `SELECT * FROM table WHERE "Ge` it will auto-complete the rest of the column name. The trick is to start the quote and it will complete the possible quoted column names. 

eg: 

![1__1_0_python2_7_-__pgcli___users_amjith_code_go_src_github_com_dogestry_dogestry___tmux_](https://cloud.githubusercontent.com/assets/49260/6810072/b5c114e6-d21b-11e4-98c8-48dc8cd80020.png)


You mentioned that you used brew to install pgcli, that is an old version of pgcli, so it might not have this feature. 

Can you install it using pip? 

You can try `pip install pgcli`. 

I'll work on upgrading the brew version to the latest.

**Comment by hammer** [comment]
Good deal will clear my brew install and try `pip`. Thanks for the quick response!
