### ISSUE TITLE
Make color scheme configurable

### ISSUE THREAD

**Issue by hammer** [amjith/pgcli#179]

**Comment by amjith** [comment]
@hammer It is configurable. Open the pgcli config file ~/.pgclirc and change the value set for `syntax_style`. 

The config file should have a list of possible colors. 

```
# Syntax Style. Possible values: manni, igor, xcode, vim, autumn, vs, rrt,
# native, perldoc, borland, tango, emacs, friendly, monokai, paraiso-dark,
# colorful, murphy, bw, pastie, paraiso-light, trac, default, fruity
```

**Comment by hammer** [comment]
Ah I used `brew install` to get `pgcli` installed and my `~/.pgclirc` doesn't have that key set by default. Any chance a solarized dark theme could be added?

**Comment by amjith** [comment]
The version available through brew is quite old. I need to update that one. 

In the mean time can you install it via pip? 

`pip install pgcli`

Right now it only has the colorschemes that are available by default in [Pygments](http://pygments.org/). Adding Solarized is possible, but it's not a high priority.

If you'd like to take a stab at it, I'd welcome a PR. :)

Here is the relevant file, if you choose to make an addition. https://github.com/amjith/pgcli/blob/master/pgcli/pgstyle.py

**Comment by hammer** [comment]
Cool filed an issue upstream: https://bitbucket.org/birkenfeld/pygments-main/issue/1098/add-solarized-and-solarized-dark-color.
