### ISSUE TITLE
Switch the string prefix matching to subsequence matching. 

### ISSUE THREAD

**Issue by amjith** [amjith/pgcli#193]
Taken from a reddit comment: http://www.reddit.com/r/programming/comments/31pkwf/mysqlcli_cli_with_autocompletion_and_syntax/cq5ftcy

>  A critical thing to notice is that the completion filtering is NOT based on the input being a string prefix of the completion (but that works too). The input needs to be a subsequence match of a completion. This is a fancy way of saying that any input characters need to be present in a completion string in the order in which they appear in the input. So abc is a subsequence of xaybgc, but not of xbyxaxxc. After the filter, a complicated sorting system ranks the completion strings so that the most relevant ones rise to the top of the menu (so you usually need to press TAB just once).

It should be a simple matter of changing this function [find_matches()](https://github.com/amjith/pgcli/blob/master/pgcli/pgcompleter.py#L160..L165) to do substring matching.

**Comment by drocco007** [comment]
I took an initial stab at the “unanchored substring” formulation of this idea, where the search term `test` will match both `test_table` and `json_test` but not `tempest`. As you intimate in your comment, this isn't a difficult change, but it does introduce some interesting UI considerations. Here's an example:

![pgcli_select_fr](https://cloud.githubusercontent.com/assets/1424858/7089345/2e4ea9b4-df69-11e4-96a2-d845b8e3a77f.png)

This doesn't seem quite right: I definitely want FROM at the top of that list, which suggests that we need some sort of prioritization to the rankings, which I don't think is supported (yet). What do you think?

**Comment by darikg** [comment]
Maybe do the vanilla prefix matching on keyword and pgspecial suggestions, but the fancier substring matching on everything else?

**Comment by amjith** [comment]
I like @darikg's solution. It's simple and might be worth trying. 

But we do need some way of ranking the suggestions in the future. I don't have any bright ideas on how to rank them, so I'm open to suggestions.

**Comment by amjith** [comment]
One other place the ranking would be useful is schemas vs tables vs functions. At the very least we need a way to distinguish them in the drop down. 

I can see us adding an opening bracket to functions, but schemas and tables are hard to distinguish. Even just a horizontal line to show the separation would be good.

**Comment by darikg** [comment]
What about using the way ptpython distinguishes files and directories?

![](https://raw.githubusercontent.com/jonathanslenders/ptpython/master/docs/images/file-completion.png)

**Comment by amjith** [comment]
Holy potatoes that is awesome!

I'd love to see the categories like that. 'Schema', 'Table', 'View' etc.

**Comment by amjith** [comment]
We should file that as a separate issue and get back to the substring matching that @drocco007 is suggesting in this issue.

**Comment by drocco007** [comment]
I have taken a crack at @darikg's suggested approach, the implementation of which you can see here: https://github.com/drocco007/pgcli/commit/1df8ca3ac2a1faca735117d14143a22bb8df2e42

This version currently doesn't work when smart completion is off (and the corresponding test is failing), as that mode makes no distinction between kinds of suggestions. I'm still pondering the best approach to handle that.

I'm also trying to decide if it makes sense to split the hardcoded functions (like DISTINCT) out from user functions; it seems like I want `SELECT MA` to suggest `MAX` but not `FORMAT` but that it might make sense to treat user functions with the unanchored substring matches.

I'd love to hear your thoughts! :)

**Comment by darikg** [comment]
This is really cool. I like using it to quickly filter a small list of suggestions to the one I want by quickly typing an obviously unique three character substring and mashing TAB, instead of having to scroll to it with the arrow keys.

I think handling the functions the way you describe makes total sense. All the built-ins have such succinct names I can't imagine substring matching being useful.
