### ISSUE TITLE
Attempt to reconnect when server connection lost

### ISSUE THREAD

**Issue by drocco007** [amjith/pgcli#196]
`psql` will attempt to reestablish a connection to the server in case of a restart or `pg_terminate_backend` call. For example, if we establish a connection to a local service

    ~$ psql -h localhost postgres postgres
    psql (9.3.5, server 9.4.1)
    WARNING: psql major version 9.3, server major version 9.4.
             Some psql features might not work.
    Type "help" for help.

    postgres=# select 1;
     ?column? 
    ----------
            1
    (1 row)

and then restart the server in another terminal, `psql` detects the broken connection and attempts to reset it:

    postgres=# select 1;
    server closed the connection unexpectedly
            This probably means the server terminated abnormally
            before or while processing the request.
    The connection to the server was lost. Attempting reset: Succeeded.
    postgres=# select 1;
     ?column? 
    ----------
            1
    (1 row)

    postgres=#

`pgcli` detects a broken connection gracefully but does not attempt to reset it:

    ~$ pgcli -h localhost postgres postgres
    Version: 0.16.3
    Chat: https://gitter.im/amjith/pgcli
    Mail: https://groups.google.com/forum/#!forum/pgcli
    Home: http://pgcli.com
    postgres> SELECT 1
    +------------+
    |   ?column? |
    |------------|
    |          1 |
    +------------+
    SELECT 1
    Command Time: 5.00679016113e-06
    Format Time: 0.000869035720825
    
The first command issued after restarting the database produces:

    postgres> SELECT 1
    server closed the connection unexpectedly
            This probably means the server terminated abnormally
            before or while processing the request.

and subsequent commands yield:

    postgres> SELECT 1
    connection already closed
    postgres> 

It would be nice if `pgcli` mimicked this behavior. In my development workflow, I frequently use the template option to CREATE DATABASE to create fast database snapshots or restore from a previous state, but this requires disconnecting active clients, so I see this behavior fairly frequently.

Notice that `psql` does not attempt to re-issue the command that failed. This is probably sensible behavior that we should preserve.

**Comment by amjith** [comment]
Yes. I like this idea. I'm sure psycopg2 throws an exception when the connection is broken, we can find out the exception type and catch that and reattempt a connection?
