### ISSUE TITLE
Better error message for failed connections

### ISSUE THREAD

**Issue by pmontrasio** [amjith/pgcli#21]
```
$ psql mydb
psql: FATAL:  role "me" does not exist
```

vs

```
$ pgcli mydb
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.10.0', 'console_scripts', 'pgcli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 572, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 552, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 744, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 388, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 76, in cli
    click.secho(e.message, err=True, fg='red')
  File "/usr/local/lib/python2.7/dist-packages/click/termui.py", line 381, in secho
    text = style(text, **styles)
TypeError: style() got an unexpected keyword argument 'err'
```

First thought: there is something wrong in my installation, too bad. I did a little googling then ```pgcli --help``` and rerun it as ```pgcli -U myuser mydb```. That worked, nevertheless, as a low priority enhancement, try mimicking psql's error messages we are all familiar with.

**Comment by amjith** [comment]
Valid point. I'll try to mimic psql errors. 

Although the error trace you pasted leads me to believe that the connection error actually triggered a different issue with the Click library used by pgcli. Are you using Windows?

**Comment by pmontrasio** [comment]
No,  I'm on Ubuntu 12.04. Can I do anything to help you debugging this error?

**Comment by amjith** [comment]
This issue should be fixed now by PR #49 and #50. Can you try installing it straight from git HEAD and see if that fixes it. 

You can install it directly from the git repo using the following command: 

`pip install -e git+git@github.com:amjith/pgcli.git#egg=pgcli`

**Comment by pmontrasio** [comment]
I got the same stack trace but probably the problem is due to #54 because I have click 3.1

**Comment by amjith** [comment]
I just merged that PR to master. Can you try it again? Sorry about that.

**Comment by amjith** [comment]
Version 0.10.1 released to PyPI. https://pypi.python.org/pypi/pgcli/0.10.1

Can you please try this and confirm if this fixes the issue?

**Comment by pmontrasio** [comment]
Works like a charm. It upgraded click to 3.3 and the new error message is nice.
