### ISSUE TITLE
Add auto-completion for tables other than public schema

### ISSUE THREAD

**Issue by amjith** [amjith/pgcli#22]
Right now the tables are only populated from the public schema. Change this to include tables from all schemas.

**Comment by xfalcox** [comment]
Or maybe include first all the schemas, and then all the tables like:

```sql
SELECT * FROM p<TAB>
```
Should show schemas like public, products and payments and put a dot in front after selection, and

```sql
SELECT * FROM products.ca<TAB>
```
Should autocomplete to the products.catalog table.

**Comment by amjith** [comment]
This going to wreck the auto-completion code. :)

Right now auto-completion assumes that a 'dot' will trigger a column name completion. But I didn't fully think about schemas. 

Thanks for the suggestion, it'll take a bit longer to implement (I think), but I'll definitely get to it.

**Comment by xfalcox** [comment]
There's a [ORM](https://github.com/jeremyevans/sequel#qualifying-identifiers-columntable-names) on rubyland who handles schemas name with double underscores, but it's kinda strange.

And I don't know about the average pguser, but on our team we have a bigdatabase, with all tables on schemas other than public, grouped by topic.

**Comment by zeha** [comment]
I'm also missing general schema support in other commands, e.g. \dt. `\dt moon.*` apparently ignores the `moon` part and just lists tables in the `public` schema.

**Comment by martin-loetzsch** [comment]
We never put anything in the  `public` schema. `pgcli` looks very promising, but missing schema support is a deal breaker for us.

**Comment by amjith** [comment]
This feature is finally available in master. Thanks to @darikg's hard work on this.

You can try it out by installing pgcli from github directly (since I haven't release the new version to PyPI yet). 

```
pip install -U -e git+https://github.com/amjith/pgcli.git#egg=pgcli
```

I would appreciate if some of you could try it out and let me know if it works to your satisfaction.

**Comment by emaillenin** [comment]
I have tested it for non-public schema. Works well and good. Can be released to PyPI.

**Comment by amjith** [comment]
This has been released to PyPI a long time ago.

**Comment by emaillenin** [comment]
I was installing it from [Homebew](http://brewformulas.org/Pgcli) couple of weeks back. This feature was not available. Should we release it to Homebrew separately?

**Comment by amjith** [comment]
Can you try `brew update` and then try `brew upgrade pgcli`? 

I had updated brew as well.
