### ISSUE TITLE
Unicode chars in results cause query to return nothing

### ISSUE THREAD

**Issue by atombender** [amjith/pgcli#24]
OS X Terminal.app. My environment:

```
# env | grep "LANG|LC" 
LANG=en_US.UTF-8
```

pgcli examples:

```
test> create table unicodechars (t text);
CREATE TABLE
test> insert into unicodechars (t) values ('e');
INSERT 0 1
test> insert into unicodechars (t) values ('é');
INSERT 0 1
test> select * from unicodechars limit 1;
+-----+
| t   |
|-----|
| e   |
+-----+
SELECT 1
test> select * from unicodechars;

test>
```

The last query returns nothing, not even an error. Also:

```
test> select 'e';
+------------+
| ?column?   |
|------------|
| e          |
+------------+
SELECT 1
test> select 'é';

test> select '😁';

test>
```

The prompt is also screwed up by  UTF-8 chars. For example, using the up-arrow to go back leads to:

```
test> selecté';
```

**Comment by amjith** [comment]
That's awful. Sorry about that. 

I'll take a look at it. Thank you for the detailed report.

**Comment by amjith** [comment]
This is fixed by pr #40. 

The fix will be released in next ver.

**Comment by atombender** [comment]
Awesome, thanks!

**Comment by amjith** [comment]
Version 0.10.1 released to PyPI. https://pypi.python.org/pypi/pgcli/0.10.1
