### ISSUE TITLE
Extremely Slow Startup

### ISSUE THREAD

**Issue by threshar** [amjith/pgcli#25]
It takes it well over a minute to start up on my database - I suspect it is due to the inefficiency of iterating over all the tables and then issuing separate selects to pull in column names. (I am seeing boatloads of queries like SELECT column_name FROM information_schema.columns WHERE\n    table_name ='')

Would likely be faster to do a single select table_name, column_name from information_schema.columns.

**Comment by amjith** [comment]
That's an awesome idea. Thanks for the suggestion. I'll add that to the next ver.
