### ISSUE TITLE
Cannot install without local Postgres

### ISSUE THREAD

**Issue by remmelt** [amjith/pgcli#29]
Installation on OSX using `pip` or `easy_install` fails with 

```
Error: pg_config executable not found.
```

I have no local installation of Postgres. I'm using a Docker container to run the database.

**Comment by cezio** [comment]
This is because pgcli requires psycopg2. Check if you have prebuild package, then installation will be able to skip this step.

**Comment by remmelt** [comment]
How do I do this?

**Comment by cezio** [comment]
See http://initd.org/psycopg/docs/install.html#install-from-a-package

But I'm not sure how fink/MacPorts installation will work with pip.

**Comment by remmelt** [comment]
Thank you!
