### ISSUE TITLE
psycopg2 v2.5 or later required

### ISSUE THREAD

**Issue by kmatzen** [amjith/pgcli#38]
psycopg2 did not support the ```with``` keyword on cursors until v2.5, I believe.  This version should be encoded in setup.py.

https://github.com/amjith/pgcli/blob/master/pgcli/pgexecute.py#L102
http://psycopg.lighthouseapp.com/projects/62710/tickets/102-cursor-is-not-compatible-with-the-with-statement

**Comment by amjith** [comment]
Thank you for the report. The PR #41 by @macobo fixes this problem. It'll be released in the next ver.
