### ISSUE TITLE
\d <table> fails

### ISSUE THREAD

**Issue by pythonhacker** [amjith/pgcli#57]
searchdb> \d cacheaddresslookup
coercing to Unicode: need string or buffer, int found

This is clearly coming from Python, when you are trying to convert a int to a string without a proper cast or format.

**Comment by amjith** [comment]
If you're using 0.10.0 of pgcli, can you try updating it. I just released 0.10.1 that fixes a bug related to unicode.

If that doesn't fix it, can you send me the output of `pip freeze`? Also is this error only happening on that particular table or is it happening for all the tables?

**Comment by macobo** [comment]
In case this is about the latest version:

You can also look at `~/.pgcli.log` and copy the output of traceback, which should be one of the last lines in the file.

**Comment by amjith** [comment]
@pythonhacker Can you please confirm if you're still seeing the issue on the latest version?

**Comment by amjith** [comment]
Version 0.14.0 released to PyPI.

Multiple fixes to unicode handling in this release. 

```
pip install -U pgcli
```
