### ISSUE TITLE
Commands with + at end fails

### ISSUE THREAD

**Issue by pythonhacker** [amjith/pgcli#58]
searchdb> \d+
ERROR:  syntax error at or near "\"
LINE 1: \d+
        ^

searchdb> \l+
ERROR:  syntax error at or near "\"
LINE 1: \l+
        ^
Looks like they are not properly parsed (Are you using Python "cmd" based REPL ?)
These are Python syntax errors clearly.

**Comment by amjith** [comment]
This is a bug. I'll take a look. 

I'm not using the 'cmd' module for the REPL. I'm using https://github.com/jonathanslenders/python-prompt-toolkit to build the repl.

**Comment by amjith** [comment]
Fixed in 0.10.3

https://pypi.python.org/pypi/pgcli/0.10.3
