### ISSUE TITLE
install page

### ISSUE THREAD

**Issue by wodabr** [amjith/pgcli#59]
Hi,

there is an error on install page, it should be 

sudo easy_install pip not sudo easy_install install pip

**Comment by jmagnusson** [comment]
I guess you meant the `sudo easy_install install pgcli` error and not `sudo easy_install install pip`, right?

**Comment by wodabr** [comment]
nope :) there's no install command in easy_install

**Comment by jmagnusson** [comment]
Re-read my question :smile:

**Comment by wodabr** [comment]
ok, I ment every occurence of easy_install on http://pgcli.com/install :)

easy_install install pgcli
sudo easy_install install pip

**Comment by jmagnusson** [comment]
Aha then you should submit your issue here https://github.com/amjith/pgcli.com/issues

**Comment by amjith** [comment]
Merged and updated. Thank you for catching that.
