### ISSUE TITLE
Error with jedi dependency

### ISSUE THREAD

**Issue by colemanm** [amjith/pgcli#64]
I just installed using `pip install pgcli` (using Python + pip from Homebrew). I get this traceback error trying to run the `pgcli` command:

```shell
~ ❯ pgcli gadm
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 2912, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 550, in _build_master
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 563, in _build_from_requirements
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 742, in resolve
pkg_resources.DistributionNotFound: jedi>=0.8.1
```

Looks like an issue with the jedi package, but it shows that it's installed:

```shell
~ ❯ pip show jedi                                                                                                                                                                  ⏎
---
Name: jedi
Version: 0.8.1-final0
Location: /usr/local/lib/python2.7/site-packages
Requires:
```

**Comment by Linell** [comment]
I'm having the same issue, also with Python/pip from Homebrew. Based off of [this](https://github.com/tkf/emacs-jedi/issues/184), I think it's got something to do with the `-final0` tag on the version. I also attempted to upgrade jedi to make sure something weird wasn't going on, but that didn't help. 

According to yolk, the version we have is all that's available.

**Comment by amjith** [comment]
Yeah this is a known issue caused by enforcing PEP 440 in the recent days. 

Please try `pip install jedi==0.8.1`, that should fix it. 

ref: https://github.com/davidhalter/jedi/issues/521

**Comment by colemanm** [comment]
Thanks, @amjith - that worked, just had to delete the temp install directory in `/private/var` first, then reinstalled.

**Comment by Linell** [comment]
:+1: worked for me

**Comment by amjith** [comment]
I've added an explicit dependency for Jedi in pgcli's setup.py file (https://github.com/amjith/pgcli/blob/master/setup.py#L28). 

This shouldn't happen anymore with pgcli version 0.10.2 and above.
