### ISSUE TITLE
weird bugs after trying out pgcli

### ISSUE THREAD

**Issue by mw44118** [amjith/pgcli#66]
I just installed pgcli.  Sometimes, \d works.  Other times it doesn't. 

    giftgram_dev> \d sent_giftgrams
    local variable 'indexdef' referenced before assignment

Also, \h doesn't work for me:

    giftgram_dev> \h alter TABLE alter COLUMN
    ERROR:  syntax error at or near "\"
    LINE 1: \h alter TABLE alter COLUMN
            ^

Thanks for starting this project!

**Comment by amjith** [comment]
Hrm. I thought I had tested all the code paths for \d but I'll start adding some tests to make sure things work ok. \d is a bit of a beast since it can be called on a table or an index or a view or sequence etc. So there is probably some branch in the code path I missed. I'll take a look. 

\h is not yet implemented. Unfortunately the back-slash commands can't be passed on directly to the database. They are implemented by `psql`, so I have to implement them one at a time to duplicate it. 

Can you tell me what is the type of sent_giftgrams in your example? Is it a table/view/seq/index or something else? 

Also what is the version of Postgres?

**Comment by mw44118** [comment]
Hey, thanks for writing back!

Here is the \d output for sent_giftgrams:

> \d sent_giftgrams
                         Table "public.sent_giftgrams"
+-------------------------+--------------------------+------------------------+
|         Column          |           Type           |       Modifiers
   |
+-------------------------+--------------------------+------------------------+
| gg_uuid                 | uuid                     | not null
  |
| recipient_email_address | email_address_type       |
   |
| sent                    | timestamp with time zone |
   |
| delivery_datetime       | timestamp with time zone |
   |
| when_to_deliver         | citext                   | not null
  |
| shipper                 | citext                   |
   |
| tracking_number         | text                     |
   |
| inserted                | timestamp with time zone | not null default
now() |
| updated                 | timestamp with time zone |
   |
| easypost_id             | text                     |
   |
| bad_tracking_data       | boolean                  |
   |
| recipient_text_number   | usa_phone_number_type    |
   |
+-------------------------+--------------------------+------------------------+
Check constraints:
    "email_giftgrams_check" CHECK (shipper IS NULL OR shipper IS NOT NULL
AND tracking_number IS NOT NULL)
    "email_giftgrams_check1" CHECK (when_to_deliver <> 'after
delivery'::citext OR shipper IS NOT NULL AND tracking_number IS NOT NULL)
    "email_or_sms_not_null" CHECK (recipient_email_address IS NOT NULL OR
recipient_text_number IS NOT NULL)
Foreign-key constraints:
    "email_giftgrams_shipper_fkey" FOREIGN KEY (shipper) REFERENCES
shippers(title) ON UPDATE CASCADE ON DELETE CASCADE
    "email_giftgrams_when_to_deliver_fkey" FOREIGN KEY (when_to_deliver)
REFERENCES when_to_deliver_allowed_values(title) ON UPDATE CASCADE ON
DELETE CASCADE
    "giftgrams_email_giftgrams_fkey" FOREIGN KEY (gg_uuid) REFERENCES
giftgrams(gg_uuid) ON UPDATE CASCADE ON DELETE CASCADE
Triggers:
    email_giftgrams_set_updated_column BEFORE UPDATE ON sent_giftgrams FOR
EACH ROW EXECUTE PROCEDURE set_updated_column()


On Wed, Jan 7, 2015 at 11:11 AM, Amjith Ramanujam <notifications@github.com>
wrote:

> Hrm. I thought I had tested all the code paths for \d but I'll start
> adding some tests to make sure things work ok. \d is a bit of a beast since
> it can be called on a table or an index or a view or sequence etc. So there
> is probably some branch in the code path I missed. I'll take a look.
>
> \h is not yet implemented. Unfortunately the back-slash commands can't be
> passed on directly to the database. They are implemented by psql, so I
> have to implement them one at a time to duplicate it.
>
> Can you tell me what is the type of sent_giftgrams in your example? Is it
> a table/view/seq/index or something else?
>
> Also what is the version of Postgres?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amjith/pgcli/issues/66#issuecomment-69044533>.
>



-- 
W. Matthew Wilson
partner
216 Software, LLC
matt@216software.com
http://216software.com

**Comment by amjith** [comment]
I found the code path that was referencing the wrong arg. It is now fixed. 

Thanks for reporting it. :green_apple:
