### ISSUE TITLE
Auto-complete double quotes for tables/columns with capital letters

### ISSUE THREAD

**Issue by kmatzen** [amjith/pgcli#67]
Is it easy to include double quotes around tables or columns that contain capital letters for auto-complete?  If quotes are not included, then postgres takes that name, puts it in all lowercase, does a case-sensitive comparison, and does not find the column or table.  Put it in quotes, it skips the lowercase step and finds it.

**Comment by amjith** [comment]
Yes it would be a useful feature and I want to do it.

It's hard to tell if it'll be easy to do or not. It'll require some parsing changes to parse_utils file. 

https://github.com/amjith/pgcli/blob/master/pgcli/packages/parseutils.py#L11

You're welcome to take a stab at it.

**Comment by qwesda** [comment]
hi,
i submitted a pull request (#83) that adds double quote escapes for table/column names with spaces, symbols, non-ascii chars and mixed-cased letters.

**Comment by amjith** [comment]
PR #83 overlaps with this feature request. It add auto-escaping to the columns/tables that are keywords or Uppercased or spaces. But it doesn't do auto-completion if the user opens a double quote. 

So I'm leaving this issue open to track that feature. :)

Cheers!

**Comment by qwesda** [comment]
Hi,

yes I noticed this too but I wasn't sure what had to changed. Maybe just the `cleanup_regex` in `parseutils.py`?
If it's something that requires more work you could give me some pointers an i'll look into it ... but maybe your quicker doing it yourself.

**Comment by amjith** [comment]
I think it should be a as simple as adding/removing stuff in the [cleanup_regex](https://github.com/amjith/pgcli/blob/master/pgcli/packages/parseutils.py#L11). 

I haven't had time to deep dive into the code since I announced it. Barely keeping up with reviewing PRs and answering Issues. You're welcome to take a stab at it, otherwise I hope to spend some time this weekend to work on it. :)

Cheers!

**Comment by amjith** [comment]
This commit afef77a6193931915d2cbf6c77b3295f6c64b57d fixes the auto-completion for quoted tables/columns that are auto-escaped.

**Comment by amjith** [comment]
This is now released in v0.12.0.

https://pypi.python.org/pypi/pgcli/0.12.0
