### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by tvon** [amjith/pgcli#73]
I have a WIP formula, I just need to figure out how to write a proper test for it.

You can try it by running

```
brew install https://raw.githubusercontent.com/tvon/homebrew/pgcli/Library/Formula/pgcli.rb
```

Any feedback would be appreciated.

**Comment by amjith** [comment]
Awesome!! I'll give it a shot. 

I notice that you have `  depends_on :postgresql`. Will that force an install of postgres via brew even if someone has postgres installed via a different mechanism (say PostgresApp or MacPorts)?

**Comment by tvon** [comment]
This is true, I can try removing that dep as it may not be necessary for psycopg to build.

**Comment by amjith** [comment]
Regarding a test. Can you just do `pgcli --help`?

**Comment by amjith** [comment]
The url for pgcli seems to point to github instead of pypi. I'd probably set it to pypi (https://pypi.python.org/packages/source/p/pgcli/pgcli-0.10.2.tar.gz) so it's similar to the rest of the packages.

**Comment by kerstin** [comment]
Ohhh, looking forward to when this works properly. (:

**Comment by tvon** [comment]
Switched to pypi and bumped to 0.10.2.

As for postgres, it is needed for psycopg2 to build, and AFAIK homebrew offers no means to check for existing/external installations outside of homebrew.

I suspect `pgcli --help` will be considered insufficient by homebrew since they don't like people using `pgcli --version` (as an example).

**Comment by amjith** [comment]
I think having 'postgres' as a dependency is reasonable in this case.

I can't think of a better test than pgcli --help since this is an interactive app. 

Thanks for updating the url to pypi. 

Is there an automated way to compute the sha for all those packages?

**Comment by amjith** [comment]
@tvon Will you be submitting a PR to homebrew or should I take over from here? 

Please let me know.

**Comment by tvon** [comment]
@amjith I went ahead and submitted https://github.com/Homebrew/homebrew/pull/35709

There is no current means to compute the shas for the dependencies, I did it the hard way... Though it could be easily scripted.

**Comment by amjith** [comment]
Thank you for submitting the PR.

After I asked you about the sha I went researching a little bit and found this script in the homebrew [cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook).

https://raw.githubusercontent.com/tdsmith/labmisc/master/mkpydeps

**Comment by tdsmith** [comment]
> I notice that you have depends_on :postgresql. Will that force an install of postgres via brew even if someone has postgres installed via a different mechanism (say PostgresApp or MacPorts)?

Two scenarios:
* If pgcli is installed from a bottle (a Homebrew-generated binary package), `depends_on :postgresql` will force an installation of Homebrew postgresql.
* If pgcli is installed from source, either because Homebrew does not provide a bottle or a user passes `--build-from-source` to `brew install`, Homebrew postgresql will only be installed if there is not another postgresql in $PATH.

Most users will experience the first condition.

**Comment by kerstin** [comment]
That doesn't really answer the original question though.
If I read your reply correctly, the answer is: _yes_, a brew install of pgcli will force a brew installation of postgresql even if the user previously installed Postgres via other means.

Could this lead to problems? (Especially for lesser experienced users.)

**Comment by tvon** [comment]
Ah, yes, installing pgcli will force a brew installation of postgresql.

Generally speaking I don't think this will cause problems, but here are some potential pitfalls (in rough order of likelihood):

1. The brew install is in the `PATH` before the non-brew install and the user relies on the command line tools.  This may or may not be an issue depending on the tools being used, but it's worth mentioning (and easy for the user to check).
2. The non-brew installation exists in the same place as homebrew.  E.g., if the user installed homebrew by the recommended means to `/usr/local` and also has postgresql installed to `/usr/local` then the postgresql installation by homebrew will fail in the final step of the installation (where it links installed files to `bin` and `lib`) and pgcli won't be installed.
3. The brew version of postgresql is protocol-incompatible with the non-brew installation.  I don't think this is even currently possible (I think you can use psql 8.3 to connect to a postgres 9.4 server).

Does that answer your question?

**Comment by amjith** [comment]
@tvon Thanks for working through the issues and addressing the requests of the homebrew maintainers. 

I see that it is now merged. I'm grateful for your help and resolve in getting this done. :)

I'll update site to include the brew install method in install pages. 

:guitar:

**Comment by amjith** [comment]
http://pgcli.com/install is updated. 

Thanks!
