### ISSUE TITLE
handle CTRL+arrow sequences

### ISSUE THREAD

**Issue by cezio** [amjith/pgcli#9]
You can jump to next word in psql with CTRL + right arrow sequence (or get back one word with left arrow). In pgcli this will produce bare sequence codes:

(arrow right, arrow left)
```
dev> sel[1;5D[1;5Cect * from 
```

**Comment by amjith** [comment]
Updated version (0.10.0) released to PyPI.

**Comment by amjith** [comment]
This is now released in v0.12.0.

https://pypi.python.org/pypi/pgcli/0.12.0
