### ISSUE TITLE
Reverse history search - CTRL+R

### ISSUE THREAD

**Issue by macobo** [amjith/pgcli#99]
Similar to the bash shell, psql allows you to search backwards in history using a substring of a previous query. We should emulate this in pgcli.

This seems like something prompt_toolkit should handle, so I'll go dig in the docs.

**Comment by amjith** [comment]
This was working out of the box in prompt_toolkit 0.25. I wonder if this is accidentally broken in 0.26. 

Try pgcli 0.11 the reverse search works fine in that version.

**Comment by amjith** [comment]
I tried adding 'load_emacs_search_bindings(registry)' to key_bindings.py but then pressing Ctrl-R crashes pgcli. 

I've sent an email to prompt_toolkit author to request help. I'll update once I hear back.

**Comment by amjith** [comment]
This is now fixed by the changes that are merged by this commit: 6018308a72dd3ad41f1d18a86e32a3c2e41da099

**Comment by amjith** [comment]
This is now released in v0.12.0.

https://pypi.python.org/pypi/pgcli/0.12.0
